server:
  #定义端口号
  port: 7099
  servlet:
    #定义项目的访问访问路径
    context-path: /consumer
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  application:
    #定义应用名称，即服务名称
    name: consumer-server
  thymeleaf:
    cache: false
  servlet:
    multipart:
      #上传文件的最大值
      max-file-size: 50MB
      #总上传数据大值
      max-request-size: 50MB

eureka:
  client:
    service-url:
      #server端配置的contextPath内容加到client端的defaultZone的访问路径端口号后面，所以client端的defaultZone:要加一个/eureka。
      defaultZone: http://localhost:8081/eureka/eureka
  instance:
    #微服务的ID,也是唯一的ID,用来被server发现
    instance-id: consumer-server
    #访问路径可以显示IP地址
    prefer-ip-address: true
#actuator配置
management:
  endpoints:
    web:
      #暴露端点
      exposure:
        include: info
    #开启info端点
  info:
    java:
      enabled: true
#openfeign配置
feign:
  client:
    config:
      default:
        #指的是建立连接后从服务器读取到可用资源所用的时间
        read-timeout: 15000
        #指的是建立连接所用的时间
        connect-timeout: 15000
        loggerLevel: full
  #替换掉JDK默认HttpURLConnection实现的Http Client
  httpclient:
    enabled: true
logging:
  level:
    com:
      example:
        blogsystemconsumer:
          service: debug
  config: classpath:logback-spring.xml
resilience4j.circuitbreaker:
  instances:
      backendA:
            #熔断器关闭时的缓冲区大小，不会限制线程的并发量
            ringBufferSizeInClosedState: 10
            #熔断器半开时的缓冲区大小，会限制线程的并发量
            ringBufferSizeInHalfOpenState: 100
            #熔断器从打开状态变为半开状态等待的时间
            waitDurationInOpenState: 1000
            #在计算失败率或慢调用率时，窗口中至少要有多少个调用。
            minimumNumberOfCalls: 3
            #表示断路器从open切换到half closed状态时,需要保持的时间
            waitInterval: 5000
            #表示故障率阈值百分比，超过这个阈值，断路器就会打开
            failureRateThreshold: 50
            #表示事件缓冲区大小
            eventConsumerBufferSize: 10
            #健康监测
            registerHealthIndicator: true