server:
  #定义端口号
  port: 9001
spring:
  application:
    #定义应用名称，即服务名称
    name: gateway-provider-server
  cloud:
    gateway:
      routes:
        - id: user_routh
          uri: http://localhost:7090
          predicates:
            - Path=/**
eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      #server端配置的contextPath内容加到client端的defaultZone的访问路径端口号后面，所以client端的defaultZone:要加一个/eureka。
      defaultZone: http://localhost:8080/eureka/eureka/
  instance:
    hostname: gateway-servivce
    #访问路径可以显示IP地址
    prefer-ip-address: true
