server:
  #定义端口号
  port: 9001
spring:
  application:
    #定义应用名称，即服务名称
    name: gateway-provider-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由动能，利用微服务名进行路由
      routes:
        - id: consumer_routh     #路由id,没有固定要求，但要唯一
          #uri: http://localhost:7090
          uri: lb://consumer-server          #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/**, /static/**      #断言，路径相同匹配的进行路由
          filter:
            AddRequestHeader=token,123
eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      #server端配置的contextPath内容加到client端的defaultZone的访问路径端口号后面，所以client端的defaultZone:要加一个/eureka。
      defaultZone: http://localhost:8080/eureka/eureka/
  instance:
    hostname: gateway-server
    instance-id: gateway-server
    #访问路径可以显示IP地址
    prefer-ip-address: true
#actuator配置
management:
  endpoints:
    #禁用其他端点
    enabled-by-default: false
    web:
      #暴露端点
      exposure:
        include: info
  endpoint:
    #开启info端点
    info:
      enabled: true
info:
  app.name: BlogSystem
  company.name: www.BlogSystem.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
