server:
  #定义端口号
  port: 8001
spring:
  application:
    #定义应用名称，即服务名称
    name: product-server
eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      #server端配置的contextPath内容加到client端的defaultZone的访问路径端口号后面，所以client端的defaultZone:要加一个/eureka。
      defaultZone: http://localhost:8080/eureka/eureka/
  instance:
    #微服务的ID,也是唯一的ID,用来被server发现
    instance-id: product-server
    #访问路径可以显示IP地址
    prefer-ip-address: true
#actuator配置
management:
  endpoints:
    #禁用其他端点
    enabled-by-default: false
    web:
      #暴露端点
      exposure:
        include: info
  endpoint:
    #开启info端点
    info:
      enabled: true
info:
  app.name: BlogSystem
  company.name: www.BlogSystem.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@