server:
  #\u5B9A\u4E49\u7AEF\u53E3\u53F7
  port: 7080
  servlet:
    #\u5B9A\u4E49\u9879\u76EE\u7684\u8BBF\u95EE\u8BBF\u95EE\u8DEF\u5F84
    context-path: /user-provider
#\u4E0B\u9762\u8FD9\u4E9B\u5185\u5BB9\u662F\u4E3A\u4E86\u8BA9MyBatis\u6620\u5C04
#\u6307\u5B9AMybatis\u7684Mapper\u6587\u4EF6
mybatis:
  mapper-locations: classpath:mappers/*xml
  #\u6307\u5B9AMybatis\u7684\u5B9E\u4F53\u76EE\u5F55
  type-aliases-package: com.example.blogsystem.entity
spring:
  application:
    #\u5B9A\u4E49\u5E94\u7528\u540D\u79F0\uFF0C\u5373\u670D\u52A1\u540D\u79F0
    name: user-provider-server
  # \u6570\u636E\u5E93\u9A71\u52A8\uFF1A
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # \u6570\u636E\u6E90\u540D\u79F0
    name: userDataSource
    # \u6570\u636E\u5E93\u8FDE\u63A5\u5730\u5740
    url: jdbc:mysql://localhost:3306/blog_user?serverTimezone=UTC
    # \u6570\u636E\u5E93\u7528\u6237\u540D&\u5BC6\u7801\uFF1A
    username: root
    password: 123
eureka:
  client:
    service-url:
      #defaultZone \u8FD9\u4E2A\u662F\u4E0D\u4F1A\u63D0\u793A\u7684\uFF0C\u6B64\u5904\u9700\u8981\u81EA\u5DF1\u5199
      #\u5B9E\u9645\u4E0A\u5C5E\u6027\u5E94\u8BE5\u662Fservice-url,\u8FD9\u4E2A\u5C5E\u6027\u662F\u4E2Amap\uFF08key-value\uFF09\u683C\u5F0F\uFF1B\u5F53key\u662FdefaultZone\u7684\u65F6\u5019\u624D\u80FD\u88AB\u89E3\u6790\uFF1B\u6240\u4EE5\u8FD9\u91CC\u6CA1\u6709\u63D0\u793A\uFF0C
      #\u4F46\u662F\u81EA\u5DF1\u8FD8\u9700\u8981\u5199\u4E00\u4E2AdefaultZone\uFF1B
      #server\u7AEF\u914D\u7F6E\u7684contextPath\u5185\u5BB9\u52A0\u5230client\u7AEF\u7684defaultZone\u7684\u8BBF\u95EE\u8DEF\u5F84\u7AEF\u53E3\u53F7\u540E\u9762\uFF0C\u6240\u4EE5client\u7AEF\u7684defaultZone:\u8981\u52A0\u4E00\u4E2A/eureka\u3002
      defaultZone: http://localhost:8080/eureka/eureka/
  instance:
    #\u5FAE\u670D\u52A1\u7684ID,\u4E5F\u662F\u552F\u4E00\u7684ID,\u7528\u6765\u88ABserver\u53D1\u73B0
    instance-id: user-provider-server
    #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740
    prefer-ip-address: true
#actuator\u914D\u7F6E
management:
  endpoints:
    #\u7981\u7528\u5176\u4ED6\u7AEF\u70B9
    enabled-by-default: false
    web:
      #\u66B4\u9732\u7AEF\u70B9
      exposure:
        include: info
  endpoint:
    #\u5F00\u542Finfo\u7AEF\u70B9
    info:
      enabled: true
info:
  app.name: BlogSystem
  company.name: www.BlogSystem.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@

